import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Notes",
  description: "Generated by create next app",
  icons: {
    icon: "/images/notes.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen bg-slate-800 w-screen py-8 overflow-y-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
